// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0yTXFUPuLlZGbfeUq2h4jGJXqMWB4SAU',
    appId: '1:822750041684:web:603d24df284fbfe4303fc1',
    messagingSenderId: '822750041684',
    projectId: 'learn-project-d2d55',
    authDomain: 'learn-project-d2d55.firebaseapp.com',
    storageBucket: 'learn-project-d2d55.appspot.com',
    measurementId: 'G-KCRB2PKNNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmIjBcu0pAMY7TPwDF2O6gnBz73SA2gtQ',
    appId: '1:822750041684:android:cc1e738492920967303fc1',
    messagingSenderId: '822750041684',
    projectId: 'learn-project-d2d55',
    storageBucket: 'learn-project-d2d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSudgOBqgmOLqIFjzi6GD75R5FzASPtMU',
    appId: '1:822750041684:ios:f16f7b6979826d09303fc1',
    messagingSenderId: '822750041684',
    projectId: 'learn-project-d2d55',
    storageBucket: 'learn-project-d2d55.appspot.com',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSudgOBqgmOLqIFjzi6GD75R5FzASPtMU',
    appId: '1:822750041684:ios:398762615d7e996d303fc1',
    messagingSenderId: '822750041684',
    projectId: 'learn-project-d2d55',
    storageBucket: 'learn-project-d2d55.appspot.com',
    iosBundleId: 'com.example.learn.RunnerTests',
  );
}
